// <auto-generated />
using System;
using HouseholdAccountBook.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseholdAccountBook.Migrations
{
    [DbContext(typeof(LocalStorageContext))]
    partial class LocalStorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("HouseholdAccountBook.DataBase.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryColorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("categoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("HouseholdAccountBook.DataBase.Data", b =>
                {
                    b.Property<int>("monthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("pricePerMonth")
                        .HasColumnType("TEXT");

                    b.HasKey("monthId");

                    b.ToTable("data");
                });

            modelBuilder.Entity("HouseholdAccountBook.DataBase.Goal", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("goalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("categoryId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("HouseholdAccountBook.DataBase.Record", b =>
                {
                    b.Property<int>("recordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("comment")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("recordDate")
                        .HasColumnType("TEXT");

                    b.HasKey("recordId");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
